name: Cypress Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: strudel-taskflows
          browser: chrome
          build: npm run build
          start: npm start
        env:
          VITE_BASE_URL: /strudel-kit/demo/